//! Soroban-portable PLONK verifier shared by all five SEP gov-type
//! contracts.
//!
//! This crate is the on-chain implementation of the verifier flow
//! whose specification + reference impl + oracle tests live in
//! `sep-xxxx-circuits::circuit::plonk::verifier` (PRs #174, #177–184).
//! Each module here mirrors a module there:
//!
//! | Soroban (this crate)            | Reference (sep-xxxx-circuits)             |
//! |---------------------------------|-------------------------------------------|
//! | `proof_format`                  | `circuit::plonk::proof_format`            |
//! | `vk_format`                     | `circuit::plonk::vk_format`               |
//! | (forthcoming) `transcript`      | `circuit::plonk::transcript`              |
//! | (forthcoming) `verifier_*`      | `circuit::plonk::verifier_*`              |
//! | (forthcoming) `verifier`        | `circuit::plonk::verifier`                |
//!
//! Each contract (`sep-anarchy`, `sep-democracy`, `sep-oligarchy`,
//! `sep-oneonone`, `sep-tyranny`) imports this crate, embeds its baked
//! VK via `include_bytes!("…vk.bin")`, and calls the top-level
//! `verifier::verify(env, vk_bytes, proof_bytes, public_inputs)` from
//! its `verify_membership` / `verify_update` entrypoints.
//!
//! ## No `std`, no `alloc`
//!
//! Soroban contracts run in WASM with no allocator beyond what the
//! SDK provides via `Env`. This crate is `#![no_std]` and avoids
//! `alloc::vec::Vec` / `alloc::string::String` — the parsers operate
//! on byte slices and write to fixed-size arrays, exactly like the
//! Rust reference.
//!
//! ## Byte layouts
//!
//! Pinned identical to the Rust reference; the parsers in this crate
//! are oracle-tested against fixtures generated by the prover-side
//! crate. If a layout constant ever drifts here, the test in
//! `vk_format::tests::pinned_offsets_match_layout_table` (or its
//! proof-side analogue) will fail before any verifier code is exercised.
//!
//! For now this crate ships only the byte-format parsers (Phase C
//! foundation). Subsequent PRs add the transcript module, challenge
//! derivation, polynomial helpers, and ultimately the top-level
//! `verifier::verify` entrypoint that contracts call.

#![no_std]

pub mod proof_format;
pub mod transcript;
pub mod verifier_challenges;
pub mod verifier;
pub mod verifier_aggregate;
pub mod verifier_aggregate_evals;
pub mod verifier_lin_poly;
pub mod verifier_polys;
pub mod vk_format;

#[cfg(test)]
mod test_fixtures;
