//! Soroban-portable PLONK verifier shared by all five SEP gov-type
//! contracts.
//!
//! This crate is the on-chain implementation of the verifier flow
//! whose specification + reference impl + oracle tests live in
//! `sep-xxxx-circuits::circuit::plonk::verifier` (PRs #174, #177–184).
//! Each module here mirrors a module there:
//!
//! | Soroban (this crate)            | Reference (sep-xxxx-circuits)             |
//! |---------------------------------|-------------------------------------------|
//! | `proof_format`                  | `circuit::plonk::proof_format`            |
//! | `vk_format`                     | `circuit::plonk::vk_format`               |
//! | (forthcoming) `transcript`      | `circuit::plonk::transcript`              |
//! | (forthcoming) `verifier_*`      | `circuit::plonk::verifier_*`              |
//! | (forthcoming) `verifier`        | `circuit::plonk::verifier`                |
//!
//! Each contract (`sep-anarchy`, `sep-democracy`, `sep-oligarchy`,
//! `sep-oneonone`, `sep-tyranny`) imports this crate, embeds its baked
//! VK via `include_bytes!("…vk.bin")`, and calls the top-level
//! `verifier::verify(env, vk_bytes, proof_bytes, public_inputs)` from
//! its `verify_membership` / `verify_update` entrypoints.
//!
//! ## No `std`
//!
//! Soroban contracts run in WASM. This crate is `#![no_std]`. The
//! parsers and arithmetic helpers operate on byte slices + fixed-size
//! arrays, matching the off-chain Rust reference shape-for-shape.
//!
//! `alloc` is enabled via `extern crate alloc` so a small interim
//! `alloc::vec::Vec<Fr>` can shuttle public inputs into
//! `verifier_polys::evaluate_pi_poly` (which takes `&[Fr]`).
//! soroban-sdk pulls `alloc` in transitively for its own
//! infrastructure, so the contract build size is unaffected.
//!
//! ## Byte layouts
//!
//! Pinned identical to the Rust reference; the parsers in this crate
//! are oracle-tested against fixtures generated by the prover-side
//! crate. If a layout constant ever drifts here, the test in
//! `vk_format::tests::pinned_offsets_match_layout_table` (or its
//! proof-side analogue) will fail before any verifier code is exercised.

#![no_std]

extern crate alloc;

pub mod proof_format;
pub mod transcript;
pub mod verifier;
pub mod verifier_aggregate;
pub mod verifier_aggregate_evals;
pub mod verifier_challenges;
pub mod verifier_lin_poly;
pub mod verifier_polys;
pub mod vk_format;

pub(crate) mod byte_helpers;

#[cfg(test)]
mod test_fixtures;
