import Foundation

public enum SEPProofGenerator {
    /// Generate a testing proving key (deterministic from seed).
    ///
    /// **WARNING**: For testing/dev only. Production apps MUST load proving keys
    /// from a keyset generated by `scripts/generate-keyset.sh`.
    /// See `OnChainService.ensureProvingKey()` for the production path.
    public static func generateTestingProvingKey(tier: SEPTier, seed: UInt64 = 42) throws -> Data {
        try RustBridge.generateTestingProvingKey(depth: tier.depth, seed: seed)
    }

    public static func generateMembershipProof(
        provingKey: Data,
        members: [SEPGroupMemberLeaf],
        secretKey: Data,
        epoch: UInt64,
        salt: Data,
        tier: SEPTier
    ) throws -> SEPMembershipProofBundle {
        try RustBridge.generateMembershipProof(
            provingKey: provingKey,
            members: members,
            secretKey: secretKey,
            epoch: epoch,
            salt: salt,
            depth: tier.depth
        )
    }

    /// Convert a compressed Groth16 proof (192 bytes) to uncompressed
    /// contract format components (proofA: 96, proofB: 192, proofC: 96).
    public static func proofToContractFormat(compressedProof: Data) throws -> SEPContractProofComponents {
        try RustBridge.proofToContractFormat(compressedProof: compressedProof)
    }

    /// Generate a testing proving key for the UpdateCircuit (#59 fix).
    ///
    /// **WARNING**: For testing/dev only. Production apps MUST load an
    /// update-circuit proving key from a keyset-v2 bundle generated by the
    /// trusted-setup ceremony.
    public static func generateTestingUpdateProvingKey(tier: SEPTier, seed: UInt64 = 42) throws -> Data {
        try RustBridge.generateTestingUpdateProvingKey(depth: tier.depth, seed: seed)
    }

    /// Generate an update-transition proof binding `(cOld, epochOld, cNew)`.
    public static func generateUpdateProof(
        provingKey: Data,
        oldMembers: [SEPGroupMemberLeaf],
        newMembers: [SEPGroupMemberLeaf],
        secretKey: Data,
        epochOld: UInt64,
        saltOld: Data,
        saltNew: Data,
        tier: SEPTier
    ) throws -> SEPUpdateProofBundle {
        try RustBridge.generateUpdateProof(
            provingKey: provingKey,
            oldMembers: oldMembers,
            newMembers: newMembers,
            secretKey: secretKey,
            epochOld: epochOld,
            saltOld: saltOld,
            saltNew: saltNew,
            depth: tier.depth
        )
    }

    /// Parse a 73-byte UpdatePublicInputs wire-format buffer into its
    /// component fields.
    public static func parseUpdatePublicInputs(wireFormat: Data) throws -> SEPUpdatePublicInputs {
        try RustBridge.parseUpdatePublicInputs(wireFormat: wireFormat)
    }
}
