import Foundation

public enum SEPProofGenerator {
    /// Generate a testing proving key (deterministic from seed).
    ///
    /// **WARNING**: For testing/dev only. Production apps MUST load proving keys
    /// from a keyset generated by `scripts/generate-keyset.sh`.
    /// See `OnChainService.ensureProvingKey()` for the production path.
    public static func generateTestingProvingKey(tier: SEPTier, seed: UInt64 = 42) throws -> Data {
        try RustBridge.generateTestingProvingKey(depth: tier.depth, seed: seed)
    }

    public static func generateMembershipProof(
        provingKey: Data,
        members: [SEPGroupMemberLeaf],
        secretKey: Data,
        epoch: UInt64,
        salt: Data,
        tier: SEPTier
    ) throws -> SEPMembershipProofBundle {
        try RustBridge.generateMembershipProof(
            provingKey: provingKey,
            members: members,
            secretKey: secretKey,
            epoch: epoch,
            salt: salt,
            depth: tier.depth
        )
    }

    /// Convert a compressed Groth16 proof (192 bytes) to uncompressed
    /// contract format components (proofA: 96, proofB: 192, proofC: 96).
    public static func proofToContractFormat(compressedProof: Data) throws -> SEPContractProofComponents {
        try RustBridge.proofToContractFormat(compressedProof: compressedProof)
    }
}
