package com.stellarmls.mls

import java.nio.ByteBuffer

/** Zero-knowledge proof generation backed by the Rust FFI. */
object SEPProofGenerator {

    /**
     * Generate a testing proving key (deterministic from seed).
     *
     * WARNING: For testing/dev only. Production apps MUST load proving keys
     * from a keyset generated by scripts/generate-keyset.sh.
     * See OnChainService.ensureProvingKey() for the production path.
     */
    fun generateTestingProvingKey(tier: SEPTier, seed: Long = 42): ByteArray {
        return RustBridge.generateTestingProvingKey(tier.depth, seed)
    }

    /** Generate a Groth16 membership proof. */
    fun generateMembershipProof(
        provingKey: ByteArray,
        members: List<SEPGroupMemberLeaf>,
        secretKey: ByteArray,
        epoch: Long,
        salt: ByteArray,
        tier: SEPTier
    ): SEPMembershipProofBundle {
        require(secretKey.size == 32) { "secret key must be 32 bytes" }
        require(salt.size == 32) { "salt must be 32 bytes" }

        val (flatPk, flatLh) = SEPCommitmentBuilder.flattenMembers(members)
        val packed = RustBridge.generateMembershipProof(
            provingKey, flatPk, flatLh, secretKey, epoch, salt, tier.depth
        )
        return unpackProofBundle(packed, epoch)
    }

    /** Decompress a proof to uncompressed contract components (A, B, C). */
    fun proofToContractFormat(compressedProof: ByteArray): SEPContractProofComponents {
        val packed = RustBridge.proofToContractFormat(compressedProof)
        return unpackContractComponents(packed)
    }

    /** Unpack [4B len][proof][4B len][commitment] into SEPMembershipProofBundle. */
    internal fun unpackProofBundle(packed: ByteArray, epoch: Long): SEPMembershipProofBundle {
        val buf = ByteBuffer.wrap(packed)
        val proofLen = buf.int
        val proof = ByteArray(proofLen)
        buf.get(proof)
        val commitmentLen = buf.int
        val commitment = ByteArray(commitmentLen)
        buf.get(commitment)
        return SEPMembershipProofBundle(
            proof = proof,
            publicInputs = SEPPublicInputs(commitment = commitment, epoch = epoch)
        )
    }

    /** Unpack [4B len][a][4B len][b][4B len][c] into SEPContractProofComponents. */
    internal fun unpackContractComponents(packed: ByteArray): SEPContractProofComponents {
        val buf = ByteBuffer.wrap(packed)
        val aLen = buf.int
        val a = ByteArray(aLen); buf.get(a)
        val bLen = buf.int
        val b = ByteArray(bLen); buf.get(b)
        val cLen = buf.int
        val c = ByteArray(cLen); buf.get(c)
        return SEPContractProofComponents(proofA = a, proofB = b, proofC = c)
    }

    /**
     * Generate a testing UpdateCircuit proving key (deterministic from seed).
     *
     * WARNING: For testing/dev only. Production apps MUST load update-circuit
     * proving keys from a keyset-v2 bundle generated by the trusted-setup
     * ceremony (Phase 8).
     */
    fun generateTestingUpdateProvingKey(tier: SEPTier, seed: Long = 42): ByteArray {
        return RustBridge.generateTestingUpdateProvingKey(tier.depth, seed)
    }

    /** Generate a Groth16 update-transition proof bound to (cOld, epochOld, cNew). */
    fun generateUpdateProof(
        provingKey: ByteArray,
        oldMembers: List<SEPGroupMemberLeaf>,
        newMembers: List<SEPGroupMemberLeaf>,
        secretKey: ByteArray,
        epochOld: Long,
        saltOld: ByteArray,
        saltNew: ByteArray,
        tier: SEPTier
    ): SEPUpdateProofBundle {
        require(secretKey.size == 32) { "secret key must be 32 bytes" }
        require(saltOld.size == 32) { "old salt must be 32 bytes" }
        require(saltNew.size == 32) { "new salt must be 32 bytes" }

        val (oldFlatPk, oldFlatLh) = SEPCommitmentBuilder.flattenMembers(oldMembers)
        val (newFlatPk, newFlatLh) = SEPCommitmentBuilder.flattenMembers(newMembers)
        val packed = RustBridge.generateUpdateProof(
            provingKey,
            oldFlatPk, oldFlatLh,
            newFlatPk, newFlatLh,
            secretKey,
            epochOld,
            saltOld, saltNew,
            tier.depth
        )
        return unpackUpdateProofBundle(packed)
    }

    /** Parse a 73-byte UpdatePublicInputs wire-format buffer. */
    fun parseUpdatePublicInputs(wireFormat: ByteArray): SEPUpdatePublicInputs {
        val packed = RustBridge.parseUpdatePublicInputs(wireFormat)
        return unpackUpdatePublicInputs(packed)
    }

    /** Unpack [4B proof_len][proof][4B pi_len][public_inputs] into SEPUpdateProofBundle. */
    internal fun unpackUpdateProofBundle(packed: ByteArray): SEPUpdateProofBundle {
        val buf = ByteBuffer.wrap(packed)
        val proofLen = buf.int
        val proof = ByteArray(proofLen); buf.get(proof)
        val piLen = buf.int
        val piBytes = ByteArray(piLen); buf.get(piBytes)
        return SEPUpdateProofBundle(proof = proof, publicInputs = parseUpdatePublicInputs(piBytes))
    }

    /**
     * Unpack `[4B c_old_len][c_old][4B epoch_old_len][epoch_old_be][4B c_new_len][c_new]`
     * into SEPUpdatePublicInputs.
     */
    internal fun unpackUpdatePublicInputs(packed: ByteArray): SEPUpdatePublicInputs {
        val buf = ByteBuffer.wrap(packed)
        val cOldLen = buf.int
        val cOld = ByteArray(cOldLen); buf.get(cOld)
        val epochLen = buf.int
        val epochBe = ByteArray(epochLen); buf.get(epochBe)
        require(epochBe.size == 8) { "epoch_old must be 8 bytes, got ${epochBe.size}" }
        val cNewLen = buf.int
        val cNew = ByteArray(cNewLen); buf.get(cNew)
        val epochOld = ByteBuffer.wrap(epochBe).long
        return SEPUpdatePublicInputs(cOld = cOld, epochOld = epochOld, cNew = cNew)
    }
}
