server {
    listen 443 ssl http2;
    server_name relay.onym.chat;

    ssl_certificate /etc/letsencrypt/live/onym.chat/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/onym.chat/privkey.pem;
    include /etc/nginx/ssl-params.conf;

    location / {
        proxy_pass http://relayer:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_read_timeout 60s;
        proxy_send_timeout 60s;
    }
}
